let courses = {
  home: [
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2023/04/feature.webp",
      title: "40 Java Interview Questions for Freshers with Clear & Concise Answers",
      author: "Tushar Vinocha",
      date: "09 Aug, 2024",
      totalMinutes: "5",
      totalViews: "192913",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2015/02/blog-2-600x314.png",
      title: "Top 30 Mini Project Ideas For College Students [UPDATED]",
      author: "Srinithi Sankar",
      date: "09 Aug, 2024",
      totalMinutes: "6",
      totalViews: "138109",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2022/12/Render-array-of-objects-in-ReactJs-1536x864.png",
      title: "How to Render an Array of Objects in React? [in 3 easy steps]",
      author: "Tarun Singh",
      date: "06 Aug, 2024",
      totalMinutes: "7",
      totalViews: "107552",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2023/06/feature-image-unique-project-ideas.jpg",
      title: "Top 10 Unique Project Ideas for College Students",
      author: "Lukesh S",
      date: "23 Jul, 2024",
      totalMinutes: "7",
      totalViews: "98359",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2023/02/animated-javascript-project-image.jpg",
      title: "30 Best JavaScript Project Ideas For You [3 Bonus Portfolio Projects]",
      author: "Saakshi Priyadarshini",
      date: "23 Jul, 2024",
      totalMinutes: "8",
      totalViews: "71356",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2023/04/image-18.png",
      title: "Crack the TCS IPA Exam: Top Questions and Exclusive Tips for Success!",
      author: "Jaishree Tomar",
      date: "23 Jul, 2024",
      totalMinutes: "7",
      totalViews: "41067",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2023/04/feature.webp",
      title: "40 Java Interview Questions for Freshers with Clear & Concise Answers",
      author: "Tushar Vinocha",
      date: "09 Aug, 2024",
      totalMinutes: "5",
      totalViews: "192913",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2015/02/blog-2-600x314.png",
      title: "Top 30 Mini Project Ideas For College Students [UPDATED]",
      author: "Srinithi Sankar",
      date: "09 Aug, 2024",
      totalMinutes: "6",
      totalViews: "138109",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2022/12/Render-array-of-objects-in-ReactJs-1536x864.png",
      title: "How to Render an Array of Objects in React? [in 3 easy steps]",
      author: "Tarun Singh",
      date: "06 Aug, 2024",
      totalMinutes: "7",
      totalViews: "107552",
    },
  ],
  fsd: [
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2023/07/person-front-computer-working-html.jpg",
      title: "Best Full-Stack Development Project Ideas in 2024",
      author: "Isha Sharma",
      date: "06 Aug, 2024",
      totalMinutes: "4",
      totalViews: "21808",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2023/07/how-long-it-would-it-take-to-learn-full-stack-development_-1536x804.webp",
      title: "How Long Would It Take to Be a Full Stack Developer?",
      author: "Meghana D",
      date: "26 Mar, 2024",
      totalMinutes: "3",
      totalViews: "18770",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2024/03/Feature-3.webp",
      title: "7 Unique Web Development Project Ideas for Beginners",
      author: "Lukesh S",
      date: "02 Apr, 2024",
      totalMinutes: "6",
      totalViews: "18704",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2023/02/DBMS1.png",
      title: "10 Best Database Management Systems For Software Developers",
      author: "Isha Sharma",
      date: "22 Mar, 2024",
      totalMinutes: "4",
      totalViews: "14902",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2023/07/person-front-computer-working-html.jpg",
      title: "Best Full-Stack Development Project Ideas in 2024",
      author: "Isha Sharma",
      date: "06 Aug, 2024",
      totalMinutes: "4",
      totalViews: "21808",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2023/07/how-long-it-would-it-take-to-learn-full-stack-development_-1536x804.webp",
      title: "How Long Would It Take to Be a Full Stack Developer?",
      author: "Meghana D",
      date: "26 Mar, 2024",
      totalMinutes: "3",
      totalViews: "18770",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2023/07/html-css-collage-concept-with-person.jpg",
      title: "Best Full-Stack Development Project Ideas in 2024",
      author: "Isha Sharma",
      date: "06 Aug, 2024",
      totalMinutes: "4",
      totalViews: "21808",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2023/07/how-long-it-would-it-take-to-learn-full-stack-development_-1536x804.webp",
      title: "How Long Would It Take to Be a Full Stack Developer?",
      author: "Meghana D",
      date: "26 Mar, 2024",
      totalMinutes: "3",
      totalViews: "18770",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2024/03/Feature-3.webp",
      title: "7 Unique Web Development Project Ideas for Beginners",
      author: "Lukesh S",
      date: "02 Apr, 2024",
      totalMinutes: "6",
      totalViews: "18704",
    },
  ],
  ds: [
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2023/11/Feature-image-Top-High-Paying-Non-Coding-Jobs-in-Data-Science.webp",
      title: "Top 10 High Paying Non-Coding Jobs in Data Science in 2024",
      author: "Isha Sharma",
      date: "23 Jul, 2024",
      totalMinutes: "6",
      totalViews: "18088",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2023/07/Real-World-Data-Science-Examples-1536x804.webp",
      title: "12 Real-World Data Science Examples: Power Of Data Science",
      author: "Lukesh S",
      date: "25 Mar, 2024",
      totalMinutes: "7",
      totalViews: "10638",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2022/06/5.-data-science-1536x804.png",
      title: "Can A Commerce Student Do Data Science?",
      author: "Saakshi Priyadarshini",
      date: "16 Apr, 2024",
      totalMinutes: "3",
      totalViews: "9594",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2023/07/image-4-1536x866.png",
      title: "Roles and Responsibilities of a Data Scientist",
      author: "Jaishree Tomar",
      date: "16 Apr, 2024",
      totalMinutes: "6",
      totalViews: "7406",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2023/09/Feature-image-Top-Product-Based-Companies-for-Data-Scientists.webp",
      title: "Top Product-Based Companies for Data Scientists in 2024",
      author: "Jaishree Tomar",
      date: "26 Mar, 2024",
      totalMinutes: "4",
      totalViews: "6965",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2023/11/Feature-image-Top-High-Paying-Non-Coding-Jobs-in-Data-Science.webp",
      title: "Top 10 High Paying Non-Coding Jobs in Data Science in 2024",
      author: "Isha Sharma",
      date: "23 Jul, 2024",
      totalMinutes: "6",
      totalViews: "18088",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2023/07/Real-World-Data-Science-Examples-1536x804.webp",
      title: "12 Real-World Data Science Examples: Power Of Data Science",
      author: "Lukesh S",
      date: "25 Mar, 2024",
      totalMinutes: "7",
      totalViews: "10638",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2022/06/5.-data-science-1536x804.png",
      title: "Can A Commerce Student Do Data Science?",
      author: "Saakshi Priyadarshini",
      date: "16 Apr, 2024",
      totalMinutes: "3",
      totalViews: "9594",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2023/07/image-4-1536x866.png",
      title: "Roles and Responsibilities of a Data Scientist",
      author: "Jaishree Tomar",
      date: "16 Apr, 2024",
      totalMinutes: "6",
      totalViews: "7406",
    },
  ],
  cbs: [
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2023/12/Feature-image-Non-Coding-Jobs-in-Cybersecurity.webp",
      title: "Non-Coding Jobs in Cybersecurity: A Comprehensive Guide",
      author: "Jaishree Tomar",
      date: "26 Mar, 2024",
      totalMinutes: "4",
      totalViews: "6668",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2022/12/Yellow-Blue-Illustration-Business-Blog-Banner-1536x864.png",
      title: "Cybersecurity Vs Ethical Hacking: Top 10 Differences",
      author: "Tushar Vinocha",
      date: "16 Apr, 2024",
      totalMinutes: "5",
      totalViews: "6648",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2023/09/Feature-image-What-Is-Hacking_-Types-of-Hacking-More.webp",
      title: "What Is Hacking? Types of Hacking & More",
      author: "Meghana D",
      date: "25 Mar, 2024",
      totalMinutes: "6",
      totalViews: "4107",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2022/12/cybersecuity-.gif",
      title: "What is Cybersecurity? Importance and its uses & the growing challenges in 2023!",
      author: "Tushar Vinocha",
      date: "04 Oct, 2023",
      totalMinutes: "4",
      totalViews: "2157",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2023/12/Feature-image-Non-Coding-Jobs-in-Cybersecurity.webp",
      title: "Non-Coding Jobs in Cybersecurity: A Comprehensive Guide",
      author: "Jaishree Tomar",
      date: "26 Mar, 2024",
      totalMinutes: "4",
      totalViews: "6668",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2022/12/Yellow-Blue-Illustration-Business-Blog-Banner-1536x864.png",
      title: "Cybersecurity Vs Ethical Hacking: Top 10 Differences",
      author: "Tushar Vinocha",
      date: "16 Apr, 2024",
      totalMinutes: "5",
      totalViews: "6648",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2023/09/Feature-image-What-Is-Hacking_-Types-of-Hacking-More.webp",
      title: "What Is Hacking? Types of Hacking & More",
      author: "Meghana D",
      date: "25 Mar, 2024",
      totalMinutes: "6",
      totalViews: "4107",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2022/12/cybersecuity-.gif",
      title: "What is Cybersecurity? Importance and its uses & the growing challenges in 2023!",
      author: "Tushar Vinocha",
      date: "04 Oct, 2023",
      totalMinutes: "4",
      totalViews: "2157",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2023/12/Feature-image-Non-Coding-Jobs-in-Cybersecurity.webp",
      title: "Non-Coding Jobs in Cybersecurity: A Comprehensive Guide",
      author: "Jaishree Tomar",
      date: "26 Mar, 2024",
      totalMinutes: "4",
      totalViews: "6668",
    },
  ],
  career: [
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2024/08/Careers-in-Data-Science.webp",
      title: "Top 10 Data Science Job Profiles (Careers in Data Science)",
      author: "Lukesh S",
      date: "06 Aug, 2024",
      totalMinutes: "7",
      totalViews: "Latest",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2024/08/devops_vs_data_science_which_career_is_best_.webp",
      title: "DevOps vs Data Science: Which Career is Best?",
      author: "Lukesh S",
      date: "03 Aug, 2024",
      totalMinutes: "5",
      totalViews: "Latest",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2023/03/Feature-Image-Power-BI-Developer-Career-Skills-Role-Salary-Scope.webp",
      title: "Power BI Developer 2024: Career, Skills, Role, Salary, Scope",
      author: "Saakshi Priyadarshini",
      date: "29 Jul, 2024",
      totalMinutes: "5",
      totalViews: "Latest",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2020/12/tumbnail-img-2-1536x774.jpg",
      title: "MEAN vs MERN: Career Growth & Salary",
      author: "admin",
      date: "29 Jul, 2024",
      totalMinutes: "5",
      totalViews: "Latest",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2024/08/Careers-in-Data-Science.webp",
      title: "Top 10 Data Science Job Profiles (Careers in Data Science)",
      author: "Lukesh S",
      date: "06 Aug, 2024",
      totalMinutes: "7",
      totalViews: "Latest",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2024/08/devops_vs_data_science_which_career_is_best_.webp",
      title: "DevOps vs Data Science: Which Career is Best?",
      author: "Lukesh S",
      date: "03 Aug, 2024",
      totalMinutes: "5",
      totalViews: "Latest",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2023/03/Feature-Image-Power-BI-Developer-Career-Skills-Role-Salary-Scope.webp",
      title: "Power BI Developer 2024: Career, Skills, Role, Salary, Scope",
      author: "Saakshi Priyadarshini",
      date: "29 Jul, 2024",
      totalMinutes: "5",
      totalViews: "Latest",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2020/12/tumbnail-img-2-1536x774.jpg",
      title: "MEAN vs MERN: Career Growth & Salary",
      author: "admin",
      date: "29 Jul, 2024",
      totalMinutes: "5",
      totalViews: "Latest",
    },
    {
      img: "https://www.guvi.in/blog/wp-content/uploads/2024/08/devops_vs_data_science_which_career_is_best_.webp",
      title: "DevOps vs Data Science: Which Career is Best?",
      author: "Lukesh S",
      date: "03 Aug, 2024",
      totalMinutes: "5",
      totalViews: "Latest",
    },
  ]
}

export default courses;